<tr align="left" valign="top"><td width="15" bgcolor="#666633"><img src="../images/pixels/hex666633.gif" alt="" width="15" height="10" /></td>
            <td width="100%" bgcolor="#666633"><table width="100%"  border="0" cellspacing="0" cellpadding="0">
              <tr>
                <td width="50%" align="left" valign="top"><span class="whiteheading"><a name="3" id="3">Links</a>  </span></td>
                <td width="50%" valign="top"align="right"><a href="#" class="bodywhite">Back to top</a> <a href="#"><img src="../images/iconbullet/anchor_green_u.gif" alt="back to top" width="8" height="8" border="0" /></a></td>
              </tr>
              <tr>
                <td colspan="2" align="left" valign="top">&nbsp;</td>
                </tr>
            </table>
			<table border="0" cellspacing="0" cellpadding="0">
			              <tr>
                <td align="left" valign="top" width="48%"><span class="bodyboldg2">1&nbsp;&nbsp;</span><a href="http://www.bbc.co.uk/history/worldwars/wwone/origins_01.shtml" title="external weblink to The Western Front Association." target="_blank" class="sourcelink"><span style="cursor:url(../icon/html.cur)">The Origins of World War One  </span></a><img src="../images/iconbullet/wwwlink.gif" alt="This website opens in a new browser window" /><br />
                    <span class="bodywhite">Part of the BBC History site, this article by Dr Gary Sheffield sets out the main causes and tensions which resulted in war.  </span></td>
                <td width="4%">&nbsp;</td>
                <td align="left" valign="top" width="48%"><span class="bodyboldg2">2&nbsp;&nbsp;</span><a href="http://www.firstworldwar.com/origins/causes.htm" title="external weblink to The Western Front Association." target="_blank" class="sourcelink"><span style="cursor:url(../icon/html.cur)">The Causes of World War One  </span></a><img src="../images/iconbullet/wwwlink.gif" alt="This website opens in a new browser window" /><br />
                    <span class="bodywhite">Part of a large American site on the Great War, this article takes a very long term view of the origins of the conflict.  </span></td>
                </tr></table></td>
            <td width="15" bgcolor="#666633"><img src="../images/pixels/hex666633.gif" alt="" width="15" height="10" /></td>
			</tr>