<table width="100%"  border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td align="left" class="anchorheading"><a name="1" id="1">Why did war break out in 1914?</a></td>
                      <td align="right"><a href="#" class="bodyblack">Back to top</a> <a href="#"><img src="../images/iconbullet/anchor_white_u.gif" alt="back to top" width="8" height="8" border="0" /></a></td>
                    </tr>
              </table><p class="bodyblack">The Great War of 1914-18 began in August 1914. The causes of this war have been debated by politicians and historians ever since. One of the few things that historians have been able to agree about is that the war was the result of many different complex factors working together. These factors meant that the situation in Europe in 1914 was very tense. This in turn allowed one crisis to spiral out of control and spark off a war that killed millions.</p>
			  <p class="bodyblack">The war was fought between rival alliances of European powers: </p>
			  <ul class="g2">
				<li><span class="bodyblack"><div style="color: black;">In 1879, Germany and Austria-Hungary formed an alliance (the Dual Alliance) that gave them great strength in the centre of Europe.</div> </span></li>
  				<li><span class="bodyblack"><div style="color: black;">In 1892, the French and the Russians formed their own strong alliance (the Dual Entente) that meant Germany now had an unfriendly power on each side.</div> </span></li>
				<li><span class="bodyblack"><div style="color: black;">Soon afterwards, Germany's most powerful soldier, General Schlieffen, drew up a plan that would allow Germany to beat France very quickly in any future war. This would then free most German troops to fight Russia in the east.</div> </span></li>
  				<li><span class="bodyblack"><div style="color: black;">By the early 1900s, the alliances had developed. The Dual Alliance had become the Triple Alliance with Italy (although Italy stayed out of the war in 1914).</div> </span></li>
				<li><span class="bodyblack"><div style="color: black;">In 1907, Britain joined Russia and France to form the Triple Entente. Britain was much less committed to this alliance than Russia or France. </div> </span></li>
			  </ul>
              
    
	<table width="100%"  border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td width="25"><img src="../images/pixels/hexFFFFFF.gif" alt="" width="1" height="1" /></td>
                       <td width="75" align="left"><a href="g2s1_bg.htm" title="Open popup window for The strength of the army" onclick="PRO_openPopupWindow('/education/greatwar/g2/g2s1_bg.htm','lcpop','620','500','scrollbars=yes,resizable=yes','yes');return document.MM_returnValue"><img src="images/thumb_g2s1bg.gif" alt="Open popup window for Triple Alliance" width="65" height="65" border="0" /></a></td>
                       <td align="left" valign="top"><span class="bodyg0"><b>Image 1</b>  </span><br />
                       <span class="bodybold">Map of Europe showing the Triple Alliance  </span><br />
     </td>
                    </tr>
				  <tr>
                      <td width="25"><img src="../images/pixels/hexFFFFFF.gif" alt="" width="1" height="1" /></td>	  
                      <td width="75"><img src="../images/pixels/hexFFFFFF.gif" alt="" width="1" height="1" /></td>
                      <td><img src="../images/pixels/hexFFFFFF.gif" alt="" width="1" height="1" /></td>
                  </tr> 
              </table>
			  
			  <table width="100%"  border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td width="25"><img src="../images/pixels/hexFFFFFF.gif" alt="" width="1" height="1" /></td>
                       <td width="75" align="left"><a href="g2s2_bg.htm" title="Open popup window for The strength of the army" onclick="PRO_openPopupWindow('/education/greatwar/g2/g2s2_bg.htm','lcpop','620','500','scrollbars=yes,resizable=yes','yes');return document.MM_returnValue"><img src="images/thumb_g2s2bg.gif" alt="Open popup window for Triple Entente" width="65" height="65" border="0" /></a></td>
                       <td align="left" valign="top"><span class="bodyg0"><b>Image 2</b>  </span><br />
                       <span class="bodybold">Map of Europe showing theTriple Entente  </span><br />
      </td>
                    </tr>
				  <tr>
                      <td width="25"><img src="../images/pixels/hexFFFFFF.gif" alt="" width="1" height="1" /></td>	  
                      <td width="75"><img src="../images/pixels/hexFFFFFF.gif" alt="" width="1" height="1" /></td>
                      <td><img src="../images/pixels/hexFFFFFF.gif" alt="" width="1" height="1" /></td>
                  </tr> 
              </table>
	          
			  <p class="bodyblack">The advantage of these alliances was that it gave the great powers a sense of security. The downside was that if the powers stuck blindly to their alliances, then a small-scale local dispute involving one power might drag the other powers in and turn into a major war.</p>
			  <p class="bodyblack">The experience of the early 1900s seemed to suggest this would not happen. For example: </p>
			  <ul class="g2">
				<li><span class="bodyblack"><div style="color: black;">In 1905 and 1911, there were disputes between the powers over colonies in North Africa.</div> </span></li>
  				<li><span class="bodyblack"><div style="color: black;">In 1908, Austria-Hungary took over the province of Bosnia, which contained many Serbs. Serbia and her ally Russia were furious, but there was no war as a result.</div> </span></li>
				<li><span class="bodyblack"><div style="color: black;">In 1912-13, there were a series of wars in the Balkans. Serbia emerged from these wars as the main victor and appeared to be a possible threat to Austria-Hungary. Even so, there was no major war.</div> </span></li></ul>
				 <p class="bodyblack">Unfortunately, this changed in 1914. The assassination of Archduke Franz Ferdinand was the trigger that set off the Great War. Franz Ferdinand was the heir to the throne of Austria-Hungary. He was assassinated on 28 June 1914 by terrorists from one of Austria-Hungary's rival powers, Serbia. Austria-Hungary blamed Serbia, even though the terrorists were not connected to the Serbian government. On 31 July 1914, Austria-Hungary declared war on Serbia.</p> 
<p class="bodyblack">At this point, the alliances came into play. Russia mobilised its army ready to help the Serbs against Austria-Hungary. Everyone knew that if Russia attacked Austria-Hungary, then the alliance system meant that Germany and France could be pulled into the war as well.</p>
<p class="bodyblack">The alliance system did not mean that a European war had to happen. Some say that it could still have been avoided - especially if Britain could have made Germany hold back from helping Austria-Hungary. Germany decided to help Austria-Hungary and declared war on Russia (1 August) and France (3 August). The German army prepared to attack France through Belgium, just as General Schlieffen had planned.</p>
			  <table width="100%"  border="0" cellspacing="0" cellpadding="0">
                    <tr>
                      <td colspan="2" align="center" class="g1_hexcolor"><img src="../images/pixels/g1_hexcolor.gif" alt="" width="680" height="2" /></td>
                    </tr>
                    <tr>
                      <td colspan="2"><img src="../images/pixels/hexFFFFFF.gif" alt="" width="680" height="10" /></td>
                    </tr>  
                    <tr>
                      <td align="left" class="anchorheading"><a name="2" id="2">How did Britain become involved in the war?</a></td>
                      <td align="right"><a href="#" class="bodyblack">Back to top</a> <a href="#"><img src="../images/iconbullet/anchor_white_u.gif" alt="back to top" width="8" height="8" border="0" /></a></td>
                    </tr>
              </table>
              <p class="bodyblack">In the late 1800s and early 1900s, Britain was often described as being in 'Splendid Isolation' from the rest of Europe. Britain had a huge empire and ruling this empire was its priority. The key to Britain's power was India with its vast resources of manpower. Britain relied heavily on Indian troops to control the empire. The highest priority for Britain was protecting the trade routes between Britain and India. Britain's large navy protected trade links with India and with the rest of the world.</p> 

<p class="bodyblack">Despite this focus on the empire, Britain was interested in events in Europe. To start with, other European countries had rival empires. Belgium and France both had large empires in Africa. There was strong rivalry between Britain and France over possessions in North Africa. By the early 1900s, Germany also had colonies in Africa and was beginning to show an interest in North Africa.</p> 

<p class="bodyblack">Another concern was Russia. For much of the 19th century, Russia wanted to take control of the Dardanelles, the area where the Black Sea opened out into the Mediterranean Sea. This would allow Russian warships and trading ships to sail easily around Europe. Russia had other ports in the north, but these tended to freeze over in winter. The problem was that the Dardanelles were owned by Turkey. Turkey and Russia had long been enemies. Britain supported Turkey against Russia. This was because Britain did not want Russian ships in the Mediterranean. The Mediterranean was part of Britain's most important trade route to India.</p> 

<p class="bodyblack">Until the early 1900s, Britain was more concerned about Russia and France than Germany. Relations between Britain and Germany were very good. This began to change, however. When Kaiser Wilhelm II took control of Germany, he was anxious for Germany to be a great power. He felt that Russia to the east and France to the west were encircling Germany. As a result, he built up his armed forces. France and Russia feared Germany and did the same. During the 1900s, all of the great powers in Europe began to build up their armies and navies.</p> 

<p class="bodyblack">British policy in Europe intended that no country in Europe should become completely dominant. If Russia, France, Germany and Austria-Hungary worried about each other, then they would be less of a threat to Britain. By about 1907 it was becoming clear to Britain that the greatest potential threat to Britain was going to be Germany. The strong economy, large population and powerful armed forces of Germany seemed to be capable of dominating Europe. As a result, Britain began to support Russia and France. Britain joined the Triple Entente.</p>

<p class="bodyblack">Despite being part of the Triple Entente, Britain was not committed to going to war in 1914. The Foreign Secretary, Sir Edward Grey, spent much of the summer of 1914 furiously trying to reassure Russia and Germany and prevent a war happening. Even when German troops invaded France and Belgium as part of the Schlieffen Plan, Britain did not have to go to war.</p> 

<p class="bodyblack">Germany hoped Britain would stay out of the war altogether. However, the Germans knew that Britain had promised to defend Belgium under the Treaty of London of 1839. The Germans wanted the British government to ignore the Treaty of London and let the German army pass through Belgium. The British government made much of their duty to protect Belgium. Belgium's ports were close to the British coast and German control of Belgium would have been seen as a serious threat to Britain. In the end, Britain refused to ignore the events of 4 August 1914, when Germany attacked France through Belgium. Within hours, Britain declared war on Germany. The Kaiser said how foolish he thought the British were. He said that Britain had gone to war for the sake of a &quot;scrap of paper&quot;.</p> 

<p class="bodyblack">Within a few more days, Britain, France and Russia (the Allies) were all officially at war with Germany and Austria-Hungary (the Central Powers). What had started as a small, local problem in the Balkans was turning into the biggest and most brutal war the world had ever seen.
</p>